mods.jei.yeet(item('ceramics:clay_barrel_unfired', 1))
mods.jei.yeet(item('ceramics:clay_barrel_unfired', 2))
mods.jei.yeet(item('ceramics:clay_barrel_unfired'))
mods.jei.yeet(item('ceramics:clay_helmet'))
mods.jei.yeet(item('ceramics:unfired_clay', 6))
mods.jei.yeet(item('ceramics:unfired_clay', 7))
mods.jei.yeet(item('ceramics:clay_chestplate'))
mods.jei.yeet(item('ceramics:clay_leggings'))
mods.jei.yeet(item('ceramics:clay_boots'))
mods.jei.yeet(item('ceramics:clay_barrel', 1))
mods.jei.yeet(item('ceramics:clay_barrel'))
mods.jei.yeet(item('ceramics:clay_barrel_unfired', 3))
