crafting.removeByOutput(item('effortlessbuilding:reach_upgrade1'))
crafting.removeByOutput(item('effortlessbuilding:reach_upgrade2'))
crafting.removeByOutput(item('effortlessbuilding:reach_upgrade3'))

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitLv')*4, metaitem('gemFlawlessDiamond')*1)
  .fluidInputs(liquid('glue')*288)
  .outputs(item('effortlessbuilding:reach_upgrade1'))
  .EUt(30)
  .duration(500)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitMv')*4, item('effortlessbuilding:reach_upgrade1')*1)
  .fluidInputs(liquid('glue')*576)
  .outputs(item('effortlessbuilding:reach_upgrade2'))
  .EUt(120)
  .duration(1000)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitHv')*4, item('effortlessbuilding:reach_upgrade2')*1)
  .fluidInputs(liquid('plastic')*576)
  .outputs(item('effortlessbuilding:reach_upgrade3'))
  .EUt(510)
  .duration(2000)
  .buildAndRegister()