mods.jei.ingredient.yeet(item('excompressum:auto_hammer'))
mods.jei.ingredient.yeet(item('excompressum:auto_compressed_hammer'))
mods.jei.ingredient.yeet(item('excompressum:auto_sieve'))
mods.jei.ingredient.yeet(item('excompressum:auto_heavy_sieve'))
mods.jei.ingredient.yeet(item('excompressum:auto_compressor'))
mods.jei.ingredient.yeet(item('excompressum:auto_compressor_rationing'))
mods.jei.ingredient.yeet(item('excompressum:chicken_stick'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_wood'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_stone'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_iron'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_gold'))
mods.jei.ingredient.yeet(item('excompressum:compressed_hammer_diamond'))
mods.jei.ingredient.yeet(item('excompressum:double_compressed_diamond_hammer'))
mods.jei.ingredient.yeet(item('excompressum:compressed_crook'))
mods.jei.ingredient.yeet(item('excompressum:iron_mesh'))
mods.jei.ingredient.yeet(item('excompressum:uncompressed_coal'))
mods.jei.ingredient.yeet(item('excompressum:bat_zapper'))
mods.jei.ingredient.yeet(item('excompressum:ore_smasher'))
mods.jei.ingredient.yeet(item('excompressum:ugly_steel_plating'))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve'))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 1))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 2))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 3))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 4))
mods.jei.ingredient.yeet(item('excompressum:heavy_sieve', 5))
mods.jei.ingredient.yeet(item('excompressum:compressed_block'))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 1))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 2))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 3))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 4))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 5))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 6))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 7))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 8))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 9))
mods.jei.ingredient.yeet(item('excompressum:compressed_block', 10))

