mods.jei.ingredient.yeet(item('integrateddynamics:coal_generator'))

mods.integrateddynamics.mechanical_squeezer.removeAll()
mods.integrateddynamics.squeezer.removeAll()
mods.integrateddynamics.squeezer.recipeBuilder()
	.input(item('integrateddynamics:menril_log'))
	.fluidOutput(fluid('menrilresin') * 1000)
	.register()
mods.integrateddynamics.squeezer.recipeBuilder()
	.input(item('minecraft:chorus_fruit_popped'))
	.fluidOutput(fluid('liquidchorus') * 1000)
	.register()
mods.integrateddynamics.mechanical_squeezer.recipeBuilder()
	.input(item('integrateddynamics:menril_log'))
	.fluidOutput(fluid('menrilresin') * 1000)
	.register()
mods.integrateddynamics.mechanical_squeezer.recipeBuilder()
	.input(item('minecraft:chorus_fruit_popped'))
	.fluidOutput(fluid('liquidchorus') * 1000)
	.register()

