crafting.removeByOutput(item('nae2:material', 1))
crafting.removeByOutput(item('nae2:material', 2))
crafting.removeByOutput(item('nae2:material', 3))
crafting.removeByOutput(item('nae2:material', 4))
crafting.removeByOutput(item('nae2:material', 5))
crafting.removeByOutput(item('nae2:material', 6))
crafting.removeByOutput(item('nae2:material', 7))
crafting.removeByOutput(item('nae2:material', 8))
crafting.removeByOutput(item('nae2:storage_cell_256k'))
crafting.removeByOutput(item('nae2:storage_cell_1024k'))
crafting.removeByOutput(item('nae2:storage_cell_4096k'))
crafting.removeByOutput(item('nae2:storage_cell_16384k'))
crafting.removeByOutput(item('nae2:storage_cell_fluid_256k'))
crafting.removeByOutput(item('nae2:storage_cell_fluid_1024k'))
crafting.removeByOutput(item('nae2:storage_cell_fluid_4096k'))
crafting.removeByOutput(item('nae2:storage_cell_fluid_16384k'))
crafting.removeByOutput(item('nae2:storage_crafting_256k'))
crafting.removeByOutput(item('nae2:storage_crafting_1024k'))
crafting.removeByOutput(item('nae2:storage_crafting_4096k'))
crafting.removeByOutput(item('nae2:storage_crafting_16384k'))


//Storage canning
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 1), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_256k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 2), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_1024k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 3), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_4096k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 4), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_16384k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 5), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_fluid_256k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 6), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_fluid_1024k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 7), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_fluid_4096k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister() 
 
mods.gregtech.canner.recipeBuilder()
  .inputs(item('nae2:material', 8), item('appliedenergistics2:material', 39))
  .outputs(item('nae2:storage_cell_fluid_16384k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('appliedenergistics2:crafting_unit'), item('nae2:material', 1))
  .outputs(item('nae2:storage_crafting_256k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()

mods.gregtech.canner.recipeBuilder()
  .inputs(item('appliedenergistics2:crafting_unit'), item('nae2:material', 2))
  .outputs(item('nae2:storage_crafting_1024k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
 mods.gregtech.canner.recipeBuilder()
  .inputs(item('appliedenergistics2:crafting_unit'), item('nae2:material', 3))
  .outputs(item('nae2:storage_crafting_4096k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
mods.gregtech.canner.recipeBuilder()
  .inputs(item('appliedenergistics2:crafting_unit'), item('nae2:material', 4))
  .outputs(item('nae2:storage_crafting_16384k'))
  .EUt(30)
  .duration(50)
  .buildAndRegister()
  
//Storage components
mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitIv')*4, item('appliedenergistics2:material', 38)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 1))
  .EUt(8190)
  .duration(150)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitLuv')*4, item('nae2:material', 1)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 2))
  .EUt(32760)
  .duration(150)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitZpm')*4, item('nae2:material', 2)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 3))
  .EUt(131070)
  .duration(150)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitUv')*4, item('nae2:material', 3)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 4))
  .EUt(524280)
  .duration(150)
  .buildAndRegister()
  
mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitIv')*4, item('appliedenergistics2:material', 57)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 5))
  .EUt(8190)
  .duration(150)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitLuv')*4, item('nae2:material', 5)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 6))
  .EUt(32760)
  .duration(150)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitZpm')*4, item('nae2:material', 6)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 7))
  .EUt(131070)
  .duration(150)
  .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
  .inputs(ore('circuitUv')*4, item('nae2:material', 7)*3, item('appliedenergistics2:material', 24)*2, item('appliedenergistics2:material', 23)*2)
  .outputs(item('nae2:material', 8))
  .EUt(524280)
  .duration(150)
  .buildAndRegister()
